In [5]:
xp  = 12
xn  = 9

def f(x):
    return 3*x+2
def bracket(xn,xp,f,imax,tol):
    i = 0
    imax = 10000
    tol = 1e-4
    while (i<imax):
      xnew = 0.5*(xp+xn)
      if(f(xnew)<tol):
        return xnew    
      if(f(xnew)<0):
        xn = xnew
      else:
        xp = xnew
      i+=1


In [9]:
def backSub(u,b):
    n = len(u)
    x = [0]*n
    ui = 0
    x[n-1] = b[n-1]/u[n-1][n-1]
    for i in range (n-2,-1,-1):
        ui = ui+u[i][i+1]*x[i+1]
        x[i] = (b[i]-ui)/u[i][i]
    return x
u = [[1,-1,2],[0,1,2],[0,0,-1]]
b = [-8,-2,-20]
x = backSub(u,b)
print(x)


[-90.0, -42.0, 20.0]


In [32]:
import numpy as np

def backSub(u, b):
    n = len(u)
    x = [0] * n
    x[n - 1] = b[n - 1] / u[n - 1][n - 1]
    for i in range(n - 2, -1, -1):
        x[i] = b[i]
        for j in range(i + 1, n):
            x[i] -= u[i][j] * x[j]
        x[i] /= u[i][i]
    return x

def gaussian_elimination(A, b):
    n = len(A)
    for k in range(0,n-1):
        for i in range(k+1, n):
            factor = A[i][k] / A[k][k]
            for j in range(k, n):
                A[i][j] -= factor * A[k][j]
            b[i] -= factor * b[k]
    print(A)
    print(b)
    x = backSub(A, b)
    return x

# Example usage:
A = np.array([[3.0, -1.0, 2.0],
              [1.0, 2.0, 3.0],
              [2.0, -2.0, -1.0]])
b = np.array([12.0, 11.0, 2.0])

solution = gaussian_elimination(A, b)
print("Solution:", solution)


[[ 3.00000000e+00 -1.00000000e+00  2.00000000e+00]
 [ 0.00000000e+00  2.33333333e+00  2.33333333e+00]
 [ 0.00000000e+00  2.22044605e-16 -1.00000000e+00]]
[12.  7. -2.]
Solution: [3.0, 0.9999999999999994, 2.0000000000000004]


In [35]:
import numpy as np

def backSub(u, b):
    n = len(u)
    x = [0] * n
    x[n - 1] = b[n - 1] / u[n - 1][n - 1]
    for i in range(n - 2, -1, -1):
        x[i] = b[i]
        for j in range(i + 1, n):
            x[i] -= u[i][j] * x[j]
        x[i] /= u[i][i]  # Corrected this line
    return x

def gaussian_elimination(A, b):
    n = len(A)
    for k in range(n - 1):
        for i in range(k + 1, n):
            factor = A[i][k] / A[k][k]
            for j in range(k, n):
                A[i][j] -= factor * A[k][j]
            b[i] -= factor * b[k]
    print(A)
    print(b)
    x = backSub(A, b)
    return x

# Example usage:
A = np.array([[3.0, -1.0, 2.0],
              [1.0, 2.0, 3.0],
              [2.0, -2.0, -1.0]])
b = np.array([12.0, 11.0, 2.0])

solution = gaussian_elimination(A, b)
print("Solution:", solution)


[[ 3.00000000e+00 -1.00000000e+00  2.00000000e+00]
 [ 0.00000000e+00  2.33333333e+00  2.33333333e+00]
 [ 0.00000000e+00  2.22044605e-16 -1.00000000e+00]]
[12.  7. -2.]
Solution: [3.0, 0.9999999999999994, 2.0000000000000004]


In [33]:
import numpy as np

def gaussian_elimination(A, b):
    n = len(A)

    augmented_matrix = np.column_stack((A, b))

    for k in range(n):
        for i in range(k + 1, n):
            factor = augmented_matrix[i, k] / augmented_matrix[k, k]
            augmented_matrix[i, k:] -= factor * augmented_matrix[k, k:]

    # Back-substitution
    x = np.zeros(n)
    for k in range(n - 1, -1, -1):
        x[k] = augmented_matrix[k, -1] / augmented_matrix[k, k]
        for i in range(k - 1, -1, -1):
            augmented_matrix[i, -1] -= augmented_matrix[i, k] * x[k]
    print(augmented_matrix)
    return x

# Example usage:
A = np.array([[3.0, -1.0, 2.0],
              [1.0, 2.0, 3.0],
              [2.0, -2.0, -1.0]])
b = np.array([12.0, 11.0, 2.0])

solution = gaussian_elimination(A, b)
print("Solution:", solution)


[[ 3.00000000e+00 -1.00000000e+00  2.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  2.33333333e+00  2.33333333e+00  2.33333333e+00]
 [ 0.00000000e+00  2.22044605e-16 -1.00000000e+00 -2.00000000e+00]]
Solution: [3. 1. 2.]


In [47]:
def tri(a, b):
    n = len(a)
    x = [[0] * n for i in range(n)]
    y = [0] * n
    x[0][1] = a[0][1] / a[0][0]
    y[0] = b[0] / a[0][0]
    for i in range(1, n - 1):
        x[i][i + 1] = a[i][i + 1] / (a[i][i] - x[i - 1][i] * a[i][i - 1])
        y[i] = (b[i] - y[i - 1] * a[i][i - 1]) / (a[i][i] - x[i - 1][i] * a[i][i - 1])
    print(x)
    print(y)
    return x, y

T = [[1, 0, 0, 0], [1, -2, 1, 0], [0, 1, -2, 1], [0, 0, 0, 1]]
b = [0, 0, 0, 1]
x, y = tri(T, b)


[[0, 0.0, 0, 0], [0, 0, -0.5, 0], [0, 0, 0, -0.6666666666666666], [0, 0, 0, 0]]
[0.0, -0.0, -0.0, 0]


In [49]:
def thomas(n, a, b, c, d):
    # Step 1: Perform Upper Triangulation
    c[0] = c[0] / b[0]
    d[0] = d[0] / b[0]

    for i in range(1, n):
        m = 1.0 / (b[i] - a[i] * c[i - 1])
        c[i] = c[i] * m
        d[i] = (d[i] - a[i] * d[i - 1]) * m

    # Step 2: Back Substitution
    x = [0] * n
    x[n - 1] = d[n - 1]

    for i in range(n - 2, -1, -1):
        x[i] = d[i] - c[i] * x[i + 1]

    return x

# Example usage:
n = 4
a = [0, 1, 1, 0]  # Sub-diagonal
b = [1, -2, -2, 1]  # Diagonal
c = [0, 1, 1, 0]  # Super-diagonal
d = [0, 0, 0, 1]  # Right-hand side

x = thomas(n, a, b, c, d)
print("Solution:", x)


Solution: [0.0, 0.3333333333333333, 0.6666666666666666, 1.0]


In [51]:
import numpy as np

def LU_decomposition(A):
    n = len(A)
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        L[i][i] = 1
        for j in range(i, n):
            U[i][j] = A[i][j]
            for k in range(i):
                U[i][j] -= L[i][k] * U[k][j]
        for j in range(i + 1, n):
            L[j][i] = A[j][i]
            for k in range(i):
                L[j][i] -= L[j][k] * U[k][i]
            L[j][i] /= U[i][i]

    return L, U

def forward_substitution(L, b):
    n = len(L)
    y = np.zeros(n)
    for i in range(n):
        y[i] = b[i]
        for j in range(i):
            y[i] -= L[i][j] * y[j]
    return y

def backward_substitution(U, y):
    n = len(U)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = y[i]
        for j in range(i + 1, n):
            x[i] -= U[i][j] * x[j]
        x[i] /= U[i][i]
    return x

# Example usage:
A = np.array([[3, -1, 2],
              [1, 2, 3],
              [2, -2, -1]])
b = np.array([12, 11, 2])

L, U = LU_decomposition(A)
print("L-Matrix:")
print(L)
print("U-Matrix:")
print(U)

y = forward_substitution(L, b)
x = backward_substitution(U, y)
print("Solution:", x)


L-Matrix:
[[ 1.          0.          0.        ]
 [ 0.33333333  1.          0.        ]
 [ 0.66666667 -0.57142857  1.        ]]
U-Matrix:
[[ 3.         -1.          2.        ]
 [ 0.          2.33333333  2.33333333]
 [ 0.          0.         -1.        ]]
Solution: [3. 1. 2.]
